feat: #17 결제 페이지
nhnacademy-be5-T3Team/front-server pull request #18
Opened 2024-04-11 07:08 UTC by parkjonggyeong18

2024-04-12 07:55 UTC, joohyun1996 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        @RequestMapping(value = "/success", method = RequestMethod.GET)
위에는 `@GetMapping` 하셨는데, 아래에는 왜 `@RequestMapping( method = RequestMethod.GET)` 하셨는지 궁금해요

2024-04-12 07:56 UTC, joohyun1996 approved these changes
수고하셨습니다.

2024-04-12 11:51 UTC, woody35545 requested changes

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        public String index(HttpServletRequest request, Model model) throws Exception {
HttpServletRequest 를 인자로 받는 이유가 있을까요?

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +            model.addAttribute("amount", 50000);
단순하게 테스트를 위해 고정된 금액을 모델에 넣으신 것으로 보이는데, 요청으로 들어온 값이 모델에 할당되도록 바꿔주시면 좋을 것 같아요.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        @RequestMapping(value = "/success", method = RequestMethod.GET)
`@GetMapping` 을 사용하면 좋을 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +            return  "/main/payments/success";
뷰의 경로 맨앞의 "/" 는 현재 저희의 타임리프 설정상 생략되어야 할 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +            return "/main/payments/fail";
뷰의 경로 맨앞의 "/" 는 현재 저희의 타임리프 설정상 생략되어야 할 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/resources/templates/main/payments/success.html
> +        const response = await fetch("http://localhost:8081/confirm", {
현재 fetch 하는 요청의 주소가 localhost로 고정되어 있어서 실제 배포환경에서는 동작하지 않습니다. profile 에 따라 다르게 요청되도록 수정해주시면 좋을 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/resources/templates/main/payments/success.html
> +        const response = await fetch("http://localhost:8081/confirm", {
또한 주소도 현재 Front 측에서 바로 해당 API 서버에 요청을 보내고 있는 것 같습니다. 이 부분도 Gateway에 요청을 보내 처리하도록 수정해주시면 좋을 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        public PaymentController(ExternalServiceAdapter externalServiceAdapter) {
`@RequiredArgsConstructor` 를 사용하면 좋을 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        @RequestMapping(value = "/fail", method = RequestMethod.GET)
`@GetMapping`을 사용하시면 좋을 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/util/ServiceUtils.java
전부 주석처리가 되어 있는데, 사용되지 않는 클래스일까요? 아니면 별도로 이유가 있으셔서 임시로 주석처리 해놓으신 걸까요??

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        public String paymentRequest(HttpServletRequest request, Model model) throws Exception {
해당 메서드의 요청 맵핑은 "GET /success" 으로 설정하셨는데, 메서드명이 paymentRequest 로 되어 있어서, 결제가 성공할 때 불리는 메서드인지 결제를 요청하는 메서드인지 구분하기 어렵습니다. 

페이먼트 위젯을 구현한 자바스크립트를 봤을 때 결제를 성공하면 /success 에 요청을 보내고 있는점과, 동일한 컨트롤러에 failPayment 메서드가 존재하는 점을 보면 아마 성공 시 수행되는 메서드를 의미하시는 것 같은데 맞을까요?

- 의도적으로 이름을 다르게 하신거라면 JavaDoc 등을 활용하여 다른 팀원들이 헷갈리지 않도록 명시해주시면 좋을 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        public String paymentRequest(HttpServletRequest request, Model model) throws Exception {
HttpServletRequest 객체에서 직접 쿼리 파라미터를 가져오는 것보다, `@RequestParam`을 이용하시면 코드가 간결해질 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        public String failPayment(HttpServletRequest request, Model model) throws Exception {
HttpServletRequest 객체에서 직접 쿼리 파라미터를 가져오는 것보다, @RequestParam을 이용하시면 코드가 간결해질 것 같습니다.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +        @RequestMapping(value = "/fail", method = RequestMethod.GET)
해당 메서드는 결제 실패시 동작하는 메서드같아 보입니다. URI를 단순히 /fail로 맵핑하기보다는 "결제"가 실패했다는 의미가 드러나도록 변경하면 좋을 것 같아요.

2024-04-12 11:51 UTC, woody35545 commented on src/main/java/com/t3t/frontserver/payment/controller/PaymentController.java
> +            return "/main/payments/checkout";
반환하시는 뷰의 경로에서 맨앞의 "/"는 제거해주셔야 합니다. 저희 타임리프 설정 확인해보시면 좋을 것 같아요

2024-04-12 12:15 UTC, woody35545 requested changes

2024-04-12 12:15 UTC, woody35545 commented on src/main/resources/templates/main/payments/success.html
> +        const response = await fetch("http://133.186.153.38:8081/confirm", {
저희가 운영하고 있는 실제 인스턴스 주소와 포트가 코드상에 드러나지 않도록하면 좋을 것 같아요.
그리고 현재처럼 배포환경으로 주소를 고정해버리면 환경에 따라 다르게 사용할 수 없습니다.

운영 환경에 따라 변경될 수 있도록 배포환경에서는 배포환경(prod profile)에 맞는 요청 주소를, 개발환경(dev profile)에서는 개발환경에 맞는 주소로 요청을 보낼 수 있도록 수정해주시면 좋을 것 같네요

그리고 현재처럼 각 서비스에 대한 API 서버를 직접 호출하지 말고 API Gateway 측에 요청을 보내도록 변경해야 하는게 좋을 것 같습니다. 현재 API Gateway 에서 Eureka 클라이언트의 상태에 따라서 사용자의 요청이 적절히 라우팅이나 로드밸런싱 되도록 설정되어 있는데, 바로 해당 API 서버를 호출하면 이러한 이점을 가져갈 수 없습니다.

2024-04-16 01:17 UTC, woody35545 approved these changes

2024-04-16 01:25 UTC, merged